# FinPay/user-service/helm/finpay-user-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: finpay-user-service
  labels:
    app: finpay-user-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: finpay-user-service
