# src/main/resources/application.yml
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finpay_auth
    username: postgres
    password: 0412@zeP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: 123456YGFVDCSAERHBFSQ5Y6TR2434TRGFV
  expiration: 86400000 # 24 hours in milliseconds
