# authentication-service/helm/finpay-auth-service/values.yaml
replicaCount: 2

image:
  repository: yourdockerhubusername/finpay-auth-service
  pullPolicy: IfNotPresent
  tag: "0.0.1-SNAPSHOT"

service:
  type: ClusterIP
  port: 8081

env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://finpay-db:5432/finpay_auth
  - name: SPRING_DATASOURCE_USERNAME
    value: postgres
  - name: SPRING_DATASOURCE_PASSWORD
    value: yourpassword
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: finpay-auth-secrets
        key: jwt.secret
  - name: JWT_EXPIRATION
    value: "86400000"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

ingress:
  enabled: false
