apiVersion: apps/v1
kind: Deployment
metadata:
  name: finpay-apigateway
  labels:
    app: finpay-apigateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: finpay-apigateway
  template:
    metadata:
      labels:
        app: finpay-apigateway
    spec:
      containers:
        - name: finpay-apigateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .valueFrom }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
              {{- else }}
              value: {{ .value | quote }}
              {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
