apiVersion: apps/v1
kind: Deployment
metadata:
  name: finpay-auth-service
  labels:
    app: finpay-auth-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: finpay-auth-service
  template:
    metadata:
      labels:
        app: finpay-auth-service
    spec:
      containers:
        - name: finpay-auth-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 8081
          env:
            {{- range .Values.env }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
