
server:
  port: 8082

spring:
  application:
    name: finpay-user-service
  datasource:
    url: jdbc:postgresql://finpay-db:5432/finpay_user
    username: postgres
    password: 0412@zeP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

# Logging Configuration
logging:
  level:
    org.springframework: INFO
    com.finpay: DEBUG
