# Application Name
spring:
  application:
    name: discovery-service

# Server Configuration
server:
  port: 8761

# Eureka Discovery Client Configuration
#eureka:
#  client:
#    enabled: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
    # Uncomment the lines below if you don't want this instance to register or fetch the registry
    # registerWithEureka: false
    # fetchRegistry: false

# Import Configuration from Config Server
  config:
    import: optional:configserver:http://localhost:9999

# Logging Level
logging:
  level:
    root: INFO
